ARG VLLM_BASE_IMAGE=vllm/vllm-openai
ARG VLLM_BASE_TAG=v0.17.0
FROM ${VLLM_BASE_IMAGE}:${VLLM_BASE_TAG}
ARG APP_DIR=/workspace/vllm-omni
WORKDIR ${APP_DIR}
COPY . .

# Install system dependencies
RUN apt-get update && \
    apt-get install -y espeak-ng ffmpeg git sox libsox-fmt-all jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN uv pip uninstall --system -y vllm || true

# Install vLLM from source at the selected commit using precompiled artifacts
ENV VLLM_PRECOMPILED_WHEEL_COMMIT=0a0a1a198be88e1782b52fa31738896468200a76
RUN uv pip install --system --force-reinstall --prerelease=allow vllm \
    --index-url https://wheels.vllm.ai/${VLLM_PRECOMPILED_WHEEL_COMMIT} \
    --extra-index-url https://pypi.org/simple/

RUN uv pip install --system ".[dev]"

RUN uv pip install --system --upgrade \
        "flashinfer-cubin==0.6.6" \
        "nvidia-cublas-cu12==12.9.1.4" \
        "numpy==2.2.6"

RUN uv pip install --system --upgrade \
    "flashinfer-jit-cache==0.6.6" \
    --index-url https://flashinfer.ai/whl/cu129
RUN ln -sf /usr/bin/python3 /usr/bin/python

ENTRYPOINT []
